### ISSUE TITLE
New Deepfakes Detection Paper presented at CVPR2023.

### ISSUE THREAD

**Issue by chuangchuangtan** [Daisy-Zhang/Awesome-Deepfakes-Detection#10]
Title : Learning on Gradients: Generalized Artifacts Representation for GAN-Generated Images Detection
Pdf  : https://openaccess.thecvf.com/content/CVPR2023/papers/Tan_Learning_on_Gradients_Generalized_Artifacts_Representation_for_GAN-Generated_Images_Detection_CVPR_2023_paper.pdf
Code: https://github.com/chuangchuangtan/LGrad

**Comment by Daisy-Zhang** [comment]
Have been updated, check it out :)
