### ISSUE TITLE
Cross-domain experiments for forgery detection

### ISSUE THREAD

**Issue by kk3lamb** [Daisy-Zhang/Awesome-Deepfakes-Detection#16]
Thanks for the great work, how is the cross domain for forgery detection done? I found many papers trained on ff++ and tested on cdf and dfdc, how is this achieved? Is it 720 videos selected from each of the four subsets of ff++? I know how the separate subsets are trained, but I don't know how to aggregate them, looking forward to your reply, thanks.

**Comment by Daisy-Zhang** [comment]
Hey, there are two ways to aggregate the videos I have seen in existing work: 1. directly aggregate the videos from all subsets. 2. only use the videos from one subset, such as Deepfakes subset. Hope this will be useful.

**Comment by kk3lamb** [comment]
Thanks for the reply, in that case it feels like merging all subsets of videos might work better?

**Comment by Daisy-Zhang** [comment]
Personally I think it depends on the method.

**Comment by kk3lamb** [comment]
Thank you for your answer, it helps me a lot!
