### ISSUE TITLE
Paper mentioned twice

### ISSUE THREAD

**Issue by SifatMd** [Daisy-Zhang/Awesome-Deepfakes-Detection#2]
Thanks for such a comprehensive list. 

I noticed "Artificial Fingerprinting for Generative Models: Rooting Deepfake Attribution in Training Data", ICCV 2021" was mentioned twice in the ICCV paper list. I think one can be removed.

Thanks.

**Comment by Daisy-Zhang** [comment]
One of them has been removed. Thanks for your careful review~
