### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by LoganCheng666** [Daisy-Zhang/Awesome-Deepfakes-Detection#4]
Thanks for your work. May I ask why the comparison content about the benchmark of all the SOTA methods was cancelled in the update after September?

**Comment by Daisy-Zhang** [comment]
Thanks. Because after collecting and comparing some recent SOTA methods, I found the experiment setting each paper used exists differences, such as datasets and metrics. And I couldn't figure out a proper and fair way to make comparisons, so I decide to cancel that part temporally.
