### ISSUE TITLE
关于FF++数据处理

### ISSUE THREAD

**Issue by LonelyPlanetIoT** [Daisy-Zhang/Awesome-Deepfakes-Detection#6]
你好，关于FF++的数据集预处理我有些疑惑，我注意到官方提供了划分json 文件，里面是些数字。但是造假视频一般有两个数字表示源视频或者目标视频，那到底是按照源视频的编号他是否属于训练集还是有别的什么方法，以及是否有讨论群之类的啊？

**Comment by Daisy-Zhang** [comment]
#5

**Comment by Daisy-Zhang** [comment]
Please refer to #5.
