### ISSUE TITLE
找到一篇论文的代码

### ISSUE THREAD

**Issue by LonelyPlanetIoT** [Daisy-Zhang/Awesome-Deepfakes-Detection#7]
ECCV 2022 UIA-ViT: Unsupervised Inconsistency-Aware Method based on Vision Transformer for Face Forgery Detection 的代码链接如下：https://github.com/wany0824/UIA-ViT。希望可以为这个仓库尽一点绵薄之力

**Comment by Daisy-Zhang** [comment]
收到，已更新，thx~

**Comment by Daisy-Zhang** [comment]
已更新，thx~
