### ISSUE TITLE
关于FF++数据集的下载

### ISSUE THREAD

**Issue by LonelyPlanetIoT** [Daisy-Zhang/Awesome-Deepfakes-Detection#8]
很抱歉再次打扰您，我最近尝试下载FF++ raw格式的数据集，但是遇到了如下图的问题。我更换了不同计算机也调整了一些设置但是都没有效果。请问还有别的方法可以下载FF++ raw格式的数据集吗
![0O J6Z~`3TX16% 1Y7_U299](https://github.com/Daisy-Zhang/Awesome-Deepfakes-Detection/assets/49614053/af7f1255-40af-401a-a03d-1abfdf1558d3)

**Comment by Daisy-Zhang** [comment]
猜测可能是网络问题，其他下载方式我也没了解过，可以查查有没有人上传过镜像备份之类的~

**Comment by LonelyPlanetIoT** [comment]
> 猜测可能是网络问题，其他下载方式我也没了解过，可以查查有没有人上传过镜像备份之类的~
是这样的，最后找境外的朋友帮忙下载的
