### ISSUE TITLE
A question about list in cvpr

### ISSUE THREAD

**Issue by LonelyPlanetIoT** [Daisy-Zhang/Awesome-Deepfakes-Detection#9]
I  do not find paper  called _**Detecting and Grounding Multi-Modal Media Manipulation**_ and **_Hierarchical Fine-Grained Image Forgery Detection and Localization_**  in  https://openaccess.thecvf.com/CVPR2023. Could you check it again?
![image](https://github.com/Daisy-Zhang/Awesome-Deepfakes-Detection/assets/49614053/a27ebff3-a0f6-4a42-98a3-df0acb4ff19d)

![image](https://github.com/Daisy-Zhang/Awesome-Deepfakes-Detection/assets/49614053/6c729882-6b33-4a36-9fc3-4d05187f437b)

**Comment by Daisy-Zhang** [comment]
Hi, I find these two papers in:
https://openaccess.thecvf.com/content/CVPR2023/html/Shao_Detecting_and_Grounding_Multi-Modal_Media_Manipulation_CVPR_2023_paper.html

https://openaccess.thecvf.com/content/CVPR2023/html/Guo_Hierarchical_Fine-Grained_Image_Forgery_Detection_and_Localization_CVPR_2023_paper.html
Please check it out.

**Comment by LonelyPlanetIoT** [comment]
> Hi, I find these two papers in: https://openaccess.thecvf.com/content/CVPR2023/html/Shao_Detecting_and_Grounding_Multi-Modal_Media_Manipulation_CVPR_2023_paper.html
> 
> https://openaccess.thecvf.com/content/CVPR2023/html/Guo_Hierarchical_Fine-Grained_Image_Forgery_Detection_and_Localization_CVPR_2023_paper.html Please check it out.

Sorry，It is my fault
